ERLANG_VERSION=${ERLANG_VERSION:-R17B05}
SCALARIS_DIR=${SCALARIS_DIR:-$HOME/scalaris}
VMS_PER_NODE=${VMS_PER_NODE:-1}
DHT_NODES_PER_VM=${DHT_NODES_PER_VM:-1}

ETCDIR=$SCALARIS_DIR/bin
BINDIR=$SCALARIS_DIR/bin
BEAMDIR=$SCALARIS_DIR/ebin
let NR_OF_NODES=$SLURM_JOB_NUM_NODES\*$VMS_PER_NODE
