-module(mime_types). 
-compile(export_all). 
t("yaws") -> {yaws, "text/html"};
t("php") -> {php, "text/html"};
t("cgi") -> {cgi, "text/html"};
t("PHP") -> {php, "text/html"};
t("CGI") -> {cgi, "text/html"};
t("AI") -> {regular, "application/postscript"};
t("AIF") -> {regular, "audio/x-aiff"};
t("AIFC") -> {regular, "audio/x-aiff"};
t("AIFF") -> {regular, "audio/x-aiff"};
t("ASC") -> {regular, "text/plain"};
t("ATOM") -> {regular, "application/atom+xml"};
t("AU") -> {regular, "audio/basic"};
t("AVI") -> {regular, "video/x-msvideo"};
t("BCPIO") -> {regular, "application/x-bcpio"};
t("BIN") -> {regular, "application/octet-stream"};
t("BMP") -> {regular, "image/bmp"};
t("BZ2") -> {regular, "application/x-bzip2"};
t("CAB") -> {regular, "application/octet-stream"};
t("CDF") -> {regular, "application/x-netcdf"};
t("CHRT") -> {regular, "application/x-kchart"};
t("CLASS") -> {regular, "application/octet-stream"};
t("CPIO") -> {regular, "application/x-cpio"};
t("CPT") -> {regular, "application/mac-compactpro"};
t("CSH") -> {regular, "application/x-csh"};
t("CSS") -> {regular, "text/css"};
t("DCR") -> {regular, "application/x-director"};
t("DIR") -> {regular, "application/x-director"};
t("DLL") -> {regular, "application/octet-stream"};
t("DMS") -> {regular, "application/octet-stream"};
t("DOC") -> {regular, "application/msword"};
t("DVI") -> {regular, "application/x-dvi"};
t("DXR") -> {regular, "application/x-director"};
t("EPS") -> {regular, "application/postscript"};
t("ERL") -> {regular, "text/plain"};
t("ETX") -> {regular, "text/x-setext"};
t("EXE") -> {regular, "application/octet-stream"};
t("EZ") -> {regular, "application/andrew-inset"};
t("FLV") -> {regular, "video/x-flv"};
t("GIF") -> {regular, "image/gif"};
t("GTAR") -> {regular, "application/x-gtar"};
t("GZ") -> {regular, "application/x-gzip"};
t("HDF") -> {regular, "application/x-hdf"};
t("HQX") -> {regular, "application/mac-binhex40"};
t("HRL") -> {regular, "text/plain"};
t("HTM") -> {regular, "text/html"};
t("HTML") -> {regular, "text/html"};
t("ICE") -> {regular, "x-conference/x-cooltalk"};
t("IEF") -> {regular, "image/ief"};
t("IGES") -> {regular, "model/iges"};
t("IGS") -> {regular, "model/iges"};
t("JAR") -> {regular, "application/octet-stream"};
t("JPE") -> {regular, "image/jpeg"};
t("JPEG") -> {regular, "image/jpeg"};
t("JPG") -> {regular, "image/jpeg"};
t("JS") -> {regular, "application/x-javascript"};
t("JSON") -> {regular, "application/json"};
t("KAR") -> {regular, "audio/midi"};
t("KIL") -> {regular, "application/x-killustrator"};
t("KML") -> {regular, "application/vnd.google-earth.kml+xml"};
t("KMZ") -> {regular, "application/vnd.google-earth.kmz"};
t("KPR") -> {regular, "application/x-kpresenter"};
t("KPT") -> {regular, "application/x-kpresenter"};
t("KSP") -> {regular, "application/x-kspread"};
t("KWD") -> {regular, "application/x-kword"};
t("KWT") -> {regular, "application/x-kword"};
t("LATEX") -> {regular, "application/x-latex"};
t("LHA") -> {regular, "application/octet-stream"};
t("LZH") -> {regular, "application/octet-stream"};
t("M3U") -> {regular, "audio/x-mpegurl"};
t("M4V") -> {regular, "video/x-m4v"};
t("MAN") -> {regular, "application/x-troff-man"};
t("ME") -> {regular, "application/x-troff-me"};
t("MESH") -> {regular, "model/mesh"};
t("MID") -> {regular, "audio/midi"};
t("MIDI") -> {regular, "audio/midi"};
t("MIF") -> {regular, "application/vnd.mif"};
t("MOV") -> {regular, "video/quicktime"};
t("MOVIE") -> {regular, "video/x-sgi-movie"};
t("MP2") -> {regular, "audio/mpeg"};
t("MP3") -> {regular, "audio/mpeg"};
t("MPE") -> {regular, "video/mpeg"};
t("MPEG") -> {regular, "video/mpeg"};
t("MPG") -> {regular, "video/mpeg"};
t("MPGA") -> {regular, "audio/mpeg"};
t("MS") -> {regular, "application/x-troff-ms"};
t("MSH") -> {regular, "model/mesh"};
t("MXU") -> {regular, "video/vnd.mpegurl"};
t("NC") -> {regular, "application/x-netcdf"};
t("ODA") -> {regular, "application/oda"};
t("OGG") -> {regular, "application/ogg"};
t("PBM") -> {regular, "image/x-portable-bitmap"};
t("PDB") -> {regular, "chemical/x-pdb"};
t("PDF") -> {regular, "application/pdf"};
t("PGM") -> {regular, "image/x-portable-graymap"};
t("PGN") -> {regular, "application/x-chess-pgn"};
t("PNG") -> {regular, "image/png"};
t("PNM") -> {regular, "image/x-portable-anymap"};
t("PPM") -> {regular, "image/x-portable-pixmap"};
t("PPT") -> {regular, "application/vnd.ms-powerpoint"};
t("PS") -> {regular, "application/postscript"};
t("QT") -> {regular, "video/quicktime"};
t("RA") -> {regular, "audio/x-realaudio"};
t("RAM") -> {regular, "audio/x-pn-realaudio"};
t("RAS") -> {regular, "image/x-cmu-raster"};
t("RGB") -> {regular, "image/x-rgb"};
t("RM") -> {regular, "audio/x-pn-realaudio"};
t("ROFF") -> {regular, "application/x-troff"};
t("RPM") -> {regular, "application/x-rpm"};
t("RSS") -> {regular, "application/rss+xml"};
t("RTF") -> {regular, "text/rtf"};
t("RTX") -> {regular, "text/richtext"};
t("SGM") -> {regular, "text/sgml"};
t("SGML") -> {regular, "text/sgml"};
t("SH") -> {regular, "application/x-sh"};
t("SHAR") -> {regular, "application/x-shar"};
t("SHTML") -> {regular, "text/html"};
t("SI") -> {regular, "text/vnd.wap.si"};
t("SIC") -> {regular, "application/vnd.wap.sic"};
t("SILO") -> {regular, "model/mesh"};
t("SIT") -> {regular, "application/x-stuffit"};
t("SKD") -> {regular, "application/x-koan"};
t("SKM") -> {regular, "application/x-koan"};
t("SKP") -> {regular, "application/x-koan"};
t("SKT") -> {regular, "application/x-koan"};
t("SL") -> {regular, "text/vnd.wap.sl"};
t("SLC") -> {regular, "application/vnd.wap.slc"};
t("SMI") -> {regular, "application/smil"};
t("SMIL") -> {regular, "application/smil"};
t("SND") -> {regular, "audio/basic"};
t("SO") -> {regular, "application/octet-stream"};
t("SPL") -> {regular, "application/x-futuresplash"};
t("SRC") -> {regular, "application/x-wais-source"};
t("SV4CPIO") -> {regular, "application/x-sv4cpio"};
t("SV4CRC") -> {regular, "application/x-sv4crc"};
t("SVG") -> {regular, "image/svg+xml"};
t("SWF") -> {regular, "application/x-shockwave-flash"};
t("T") -> {regular, "application/x-troff"};
t("TAR") -> {regular, "application/x-tar"};
t("TCL") -> {regular, "application/x-tcl"};
t("TEX") -> {regular, "application/x-tex"};
t("TEXI") -> {regular, "application/x-texinfo"};
t("TEXINFO") -> {regular, "application/x-texinfo"};
t("TGZ") -> {regular, "application/x-gzip"};
t("TIF") -> {regular, "image/tiff"};
t("TIFF") -> {regular, "image/tiff"};
t("TR") -> {regular, "application/x-troff"};
t("TS") -> {regular, "video/mp2t"};
t("TSV") -> {regular, "text/tab-separated-values"};
t("TXT") -> {regular, "text/plain"};
t("USTAR") -> {regular, "application/x-ustar"};
t("VCD") -> {regular, "application/x-cdlink"};
t("VRML") -> {regular, "model/vrml"};
t("WAV") -> {regular, "audio/x-wav"};
t("WBMP") -> {regular, "image/vnd.wap.wbmp"};
t("WBXML") -> {regular, "application/vnd.wap.wbxml"};
t("WML") -> {regular, "text/vnd.wap.wml"};
t("WMLC") -> {regular, "application/vnd.wap.wmlc"};
t("WMLS") -> {regular, "text/vnd.wap.wmlscript"};
t("WMLSC") -> {regular, "application/vnd.wap.wmlscriptc"};
t("WMV") -> {regular, "video/x-ms-wmv"};
t("WRL") -> {regular, "model/vrml"};
t("XBM") -> {regular, "image/x-xbitmap"};
t("XHTML") -> {regular, "application/xhtml+xml"};
t("XLS") -> {regular, "application/vnd.ms-excel"};
t("XML") -> {regular, "text/xml"};
t("XPM") -> {regular, "image/x-xpixmap"};
t("XSL") -> {regular, "text/xml"};
t("XWD") -> {regular, "image/x-xwindowdump"};
t("XYZ") -> {regular, "chemical/x-xyz"};
t("ZIP") -> {regular, "application/zip"};
t("ai") -> {regular, "application/postscript"};
t("aif") -> {regular, "audio/x-aiff"};
t("aifc") -> {regular, "audio/x-aiff"};
t("aiff") -> {regular, "audio/x-aiff"};
t("asc") -> {regular, "text/plain"};
t("atom") -> {regular, "application/atom+xml"};
t("au") -> {regular, "audio/basic"};
t("avi") -> {regular, "video/x-msvideo"};
t("bcpio") -> {regular, "application/x-bcpio"};
t("bin") -> {regular, "application/octet-stream"};
t("bmp") -> {regular, "image/bmp"};
t("bz2") -> {regular, "application/x-bzip2"};
t("cab") -> {regular, "application/octet-stream"};
t("cdf") -> {regular, "application/x-netcdf"};
t("chrt") -> {regular, "application/x-kchart"};
t("class") -> {regular, "application/octet-stream"};
t("cpio") -> {regular, "application/x-cpio"};
t("cpt") -> {regular, "application/mac-compactpro"};
t("csh") -> {regular, "application/x-csh"};
t("css") -> {regular, "text/css"};
t("dcr") -> {regular, "application/x-director"};
t("dir") -> {regular, "application/x-director"};
t("dll") -> {regular, "application/octet-stream"};
t("dms") -> {regular, "application/octet-stream"};
t("doc") -> {regular, "application/msword"};
t("dvi") -> {regular, "application/x-dvi"};
t("dxr") -> {regular, "application/x-director"};
t("eps") -> {regular, "application/postscript"};
t("erl") -> {regular, "text/plain"};
t("etx") -> {regular, "text/x-setext"};
t("exe") -> {regular, "application/octet-stream"};
t("ez") -> {regular, "application/andrew-inset"};
t("flv") -> {regular, "video/x-flv"};
t("gif") -> {regular, "image/gif"};
t("gtar") -> {regular, "application/x-gtar"};
t("gz") -> {regular, "application/x-gzip"};
t("hdf") -> {regular, "application/x-hdf"};
t("hqx") -> {regular, "application/mac-binhex40"};
t("hrl") -> {regular, "text/plain"};
t("htm") -> {regular, "text/html"};
t("html") -> {regular, "text/html"};
t("ice") -> {regular, "x-conference/x-cooltalk"};
t("ief") -> {regular, "image/ief"};
t("iges") -> {regular, "model/iges"};
t("igs") -> {regular, "model/iges"};
t("jar") -> {regular, "application/octet-stream"};
t("jpe") -> {regular, "image/jpeg"};
t("jpeg") -> {regular, "image/jpeg"};
t("jpg") -> {regular, "image/jpeg"};
t("js") -> {regular, "application/x-javascript"};
t("json") -> {regular, "application/json"};
t("kar") -> {regular, "audio/midi"};
t("kil") -> {regular, "application/x-killustrator"};
t("kml") -> {regular, "application/vnd.google-earth.kml+xml"};
t("kmz") -> {regular, "application/vnd.google-earth.kmz"};
t("kpr") -> {regular, "application/x-kpresenter"};
t("kpt") -> {regular, "application/x-kpresenter"};
t("ksp") -> {regular, "application/x-kspread"};
t("kwd") -> {regular, "application/x-kword"};
t("kwt") -> {regular, "application/x-kword"};
t("latex") -> {regular, "application/x-latex"};
t("lha") -> {regular, "application/octet-stream"};
t("lzh") -> {regular, "application/octet-stream"};
t("m3u") -> {regular, "audio/x-mpegurl"};
t("m4v") -> {regular, "video/x-m4v"};
t("man") -> {regular, "application/x-troff-man"};
t("me") -> {regular, "application/x-troff-me"};
t("mesh") -> {regular, "model/mesh"};
t("mid") -> {regular, "audio/midi"};
t("midi") -> {regular, "audio/midi"};
t("mif") -> {regular, "application/vnd.mif"};
t("mov") -> {regular, "video/quicktime"};
t("movie") -> {regular, "video/x-sgi-movie"};
t("mp2") -> {regular, "audio/mpeg"};
t("mp3") -> {regular, "audio/mpeg"};
t("mpe") -> {regular, "video/mpeg"};
t("mpeg") -> {regular, "video/mpeg"};
t("mpg") -> {regular, "video/mpeg"};
t("mpga") -> {regular, "audio/mpeg"};
t("ms") -> {regular, "application/x-troff-ms"};
t("msh") -> {regular, "model/mesh"};
t("mxu") -> {regular, "video/vnd.mpegurl"};
t("nc") -> {regular, "application/x-netcdf"};
t("oda") -> {regular, "application/oda"};
t("ogg") -> {regular, "application/ogg"};
t("pbm") -> {regular, "image/x-portable-bitmap"};
t("pdb") -> {regular, "chemical/x-pdb"};
t("pdf") -> {regular, "application/pdf"};
t("pgm") -> {regular, "image/x-portable-graymap"};
t("pgn") -> {regular, "application/x-chess-pgn"};
t("png") -> {regular, "image/png"};
t("pnm") -> {regular, "image/x-portable-anymap"};
t("ppm") -> {regular, "image/x-portable-pixmap"};
t("ppt") -> {regular, "application/vnd.ms-powerpoint"};
t("ps") -> {regular, "application/postscript"};
t("qt") -> {regular, "video/quicktime"};
t("ra") -> {regular, "audio/x-realaudio"};
t("ram") -> {regular, "audio/x-pn-realaudio"};
t("ras") -> {regular, "image/x-cmu-raster"};
t("rgb") -> {regular, "image/x-rgb"};
t("rm") -> {regular, "audio/x-pn-realaudio"};
t("roff") -> {regular, "application/x-troff"};
t("rpm") -> {regular, "application/x-rpm"};
t("rss") -> {regular, "application/rss+xml"};
t("rtf") -> {regular, "text/rtf"};
t("rtx") -> {regular, "text/richtext"};
t("sgm") -> {regular, "text/sgml"};
t("sgml") -> {regular, "text/sgml"};
t("sh") -> {regular, "application/x-sh"};
t("shar") -> {regular, "application/x-shar"};
t("shtml") -> {regular, "text/html"};
t("si") -> {regular, "text/vnd.wap.si"};
t("sic") -> {regular, "application/vnd.wap.sic"};
t("silo") -> {regular, "model/mesh"};
t("sit") -> {regular, "application/x-stuffit"};
t("skd") -> {regular, "application/x-koan"};
t("skm") -> {regular, "application/x-koan"};
t("skp") -> {regular, "application/x-koan"};
t("skt") -> {regular, "application/x-koan"};
t("sl") -> {regular, "text/vnd.wap.sl"};
t("slc") -> {regular, "application/vnd.wap.slc"};
t("smi") -> {regular, "application/smil"};
t("smil") -> {regular, "application/smil"};
t("snd") -> {regular, "audio/basic"};
t("so") -> {regular, "application/octet-stream"};
t("spl") -> {regular, "application/x-futuresplash"};
t("src") -> {regular, "application/x-wais-source"};
t("sv4cpio") -> {regular, "application/x-sv4cpio"};
t("sv4crc") -> {regular, "application/x-sv4crc"};
t("svg") -> {regular, "image/svg+xml"};
t("swf") -> {regular, "application/x-shockwave-flash"};
t("t") -> {regular, "application/x-troff"};
t("tar") -> {regular, "application/x-tar"};
t("tcl") -> {regular, "application/x-tcl"};
t("tex") -> {regular, "application/x-tex"};
t("texi") -> {regular, "application/x-texinfo"};
t("texinfo") -> {regular, "application/x-texinfo"};
t("tgz") -> {regular, "application/x-gzip"};
t("tif") -> {regular, "image/tiff"};
t("tiff") -> {regular, "image/tiff"};
t("tr") -> {regular, "application/x-troff"};
t("ts") -> {regular, "video/mp2t"};
t("tsv") -> {regular, "text/tab-separated-values"};
t("txt") -> {regular, "text/plain"};
t("ustar") -> {regular, "application/x-ustar"};
t("vcd") -> {regular, "application/x-cdlink"};
t("vrml") -> {regular, "model/vrml"};
t("wav") -> {regular, "audio/x-wav"};
t("wbmp") -> {regular, "image/vnd.wap.wbmp"};
t("wbxml") -> {regular, "application/vnd.wap.wbxml"};
t("wml") -> {regular, "text/vnd.wap.wml"};
t("wmlc") -> {regular, "application/vnd.wap.wmlc"};
t("wmls") -> {regular, "text/vnd.wap.wmlscript"};
t("wmlsc") -> {regular, "application/vnd.wap.wmlscriptc"};
t("wmv") -> {regular, "video/x-ms-wmv"};
t("wrl") -> {regular, "model/vrml"};
t("xbm") -> {regular, "image/x-xbitmap"};
t("xhtml") -> {regular, "application/xhtml+xml"};
t("xls") -> {regular, "application/vnd.ms-excel"};
t("xml") -> {regular, "text/xml"};
t("xpm") -> {regular, "image/x-xpixmap"};
t("xsl") -> {regular, "text/xml"};
t("xwd") -> {regular, "image/x-xwindowdump"};
t("xyz") -> {regular, "chemical/x-xyz"};
t("zip") -> {regular, "application/zip"};
t(_) -> {regular, "text/plain"}.


revt("sway") -> {yaws, "yaws", "text/html"};
revt("php") -> {php, "php", "text/html"};
revt("igc") -> {cgi, "cgi", "text/html"};
revt("PHP") -> {php, "PHP", "text/html"};
revt("IGC") -> {cgi, "CGI", "text/html"};
revt("IA") -> {regular, "AI", "application/postscript"};
revt("FIA") -> {regular, "AIF", "audio/x-aiff"};
revt("CFIA") -> {regular, "AIFC", "audio/x-aiff"};
revt("FFIA") -> {regular, "AIFF", "audio/x-aiff"};
revt("CSA") -> {regular, "ASC", "text/plain"};
revt("MOTA") -> {regular, "ATOM", "application/atom+xml"};
revt("UA") -> {regular, "AU", "audio/basic"};
revt("IVA") -> {regular, "AVI", "video/x-msvideo"};
revt("OIPCB") -> {regular, "BCPIO", "application/x-bcpio"};
revt("NIB") -> {regular, "BIN", "application/octet-stream"};
revt("PMB") -> {regular, "BMP", "image/bmp"};
revt("2ZB") -> {regular, "BZ2", "application/x-bzip2"};
revt("BAC") -> {regular, "CAB", "application/octet-stream"};
revt("FDC") -> {regular, "CDF", "application/x-netcdf"};
revt("TRHC") -> {regular, "CHRT", "application/x-kchart"};
revt("SSALC") -> {regular, "CLASS", "application/octet-stream"};
revt("OIPC") -> {regular, "CPIO", "application/x-cpio"};
revt("TPC") -> {regular, "CPT", "application/mac-compactpro"};
revt("HSC") -> {regular, "CSH", "application/x-csh"};
revt("SSC") -> {regular, "CSS", "text/css"};
revt("RCD") -> {regular, "DCR", "application/x-director"};
revt("RID") -> {regular, "DIR", "application/x-director"};
revt("LLD") -> {regular, "DLL", "application/octet-stream"};
revt("SMD") -> {regular, "DMS", "application/octet-stream"};
revt("COD") -> {regular, "DOC", "application/msword"};
revt("IVD") -> {regular, "DVI", "application/x-dvi"};
revt("RXD") -> {regular, "DXR", "application/x-director"};
revt("SPE") -> {regular, "EPS", "application/postscript"};
revt("LRE") -> {regular, "ERL", "text/plain"};
revt("XTE") -> {regular, "ETX", "text/x-setext"};
revt("EXE") -> {regular, "EXE", "application/octet-stream"};
revt("ZE") -> {regular, "EZ", "application/andrew-inset"};
revt("VLF") -> {regular, "FLV", "video/x-flv"};
revt("FIG") -> {regular, "GIF", "image/gif"};
revt("RATG") -> {regular, "GTAR", "application/x-gtar"};
revt("ZG") -> {regular, "GZ", "application/x-gzip"};
revt("FDH") -> {regular, "HDF", "application/x-hdf"};
revt("XQH") -> {regular, "HQX", "application/mac-binhex40"};
revt("LRH") -> {regular, "HRL", "text/plain"};
revt("MTH") -> {regular, "HTM", "text/html"};
revt("LMTH") -> {regular, "HTML", "text/html"};
revt("ECI") -> {regular, "ICE", "x-conference/x-cooltalk"};
revt("FEI") -> {regular, "IEF", "image/ief"};
revt("SEGI") -> {regular, "IGES", "model/iges"};
revt("SGI") -> {regular, "IGS", "model/iges"};
revt("RAJ") -> {regular, "JAR", "application/octet-stream"};
revt("EPJ") -> {regular, "JPE", "image/jpeg"};
revt("GEPJ") -> {regular, "JPEG", "image/jpeg"};
revt("GPJ") -> {regular, "JPG", "image/jpeg"};
revt("SJ") -> {regular, "JS", "application/x-javascript"};
revt("NOSJ") -> {regular, "JSON", "application/json"};
revt("RAK") -> {regular, "KAR", "audio/midi"};
revt("LIK") -> {regular, "KIL", "application/x-killustrator"};
revt("LMK") -> {regular, "KML", "application/vnd.google-earth.kml+xml"};
revt("ZMK") -> {regular, "KMZ", "application/vnd.google-earth.kmz"};
revt("RPK") -> {regular, "KPR", "application/x-kpresenter"};
revt("TPK") -> {regular, "KPT", "application/x-kpresenter"};
revt("PSK") -> {regular, "KSP", "application/x-kspread"};
revt("DWK") -> {regular, "KWD", "application/x-kword"};
revt("TWK") -> {regular, "KWT", "application/x-kword"};
revt("XETAL") -> {regular, "LATEX", "application/x-latex"};
revt("AHL") -> {regular, "LHA", "application/octet-stream"};
revt("HZL") -> {regular, "LZH", "application/octet-stream"};
revt("U3M") -> {regular, "M3U", "audio/x-mpegurl"};
revt("V4M") -> {regular, "M4V", "video/x-m4v"};
revt("NAM") -> {regular, "MAN", "application/x-troff-man"};
revt("EM") -> {regular, "ME", "application/x-troff-me"};
revt("HSEM") -> {regular, "MESH", "model/mesh"};
revt("DIM") -> {regular, "MID", "audio/midi"};
revt("IDIM") -> {regular, "MIDI", "audio/midi"};
revt("FIM") -> {regular, "MIF", "application/vnd.mif"};
revt("VOM") -> {regular, "MOV", "video/quicktime"};
revt("EIVOM") -> {regular, "MOVIE", "video/x-sgi-movie"};
revt("2PM") -> {regular, "MP2", "audio/mpeg"};
revt("3PM") -> {regular, "MP3", "audio/mpeg"};
revt("EPM") -> {regular, "MPE", "video/mpeg"};
revt("GEPM") -> {regular, "MPEG", "video/mpeg"};
revt("GPM") -> {regular, "MPG", "video/mpeg"};
revt("AGPM") -> {regular, "MPGA", "audio/mpeg"};
revt("SM") -> {regular, "MS", "application/x-troff-ms"};
revt("HSM") -> {regular, "MSH", "model/mesh"};
revt("UXM") -> {regular, "MXU", "video/vnd.mpegurl"};
revt("CN") -> {regular, "NC", "application/x-netcdf"};
revt("ADO") -> {regular, "ODA", "application/oda"};
revt("GGO") -> {regular, "OGG", "application/ogg"};
revt("MBP") -> {regular, "PBM", "image/x-portable-bitmap"};
revt("BDP") -> {regular, "PDB", "chemical/x-pdb"};
revt("FDP") -> {regular, "PDF", "application/pdf"};
revt("MGP") -> {regular, "PGM", "image/x-portable-graymap"};
revt("NGP") -> {regular, "PGN", "application/x-chess-pgn"};
revt("GNP") -> {regular, "PNG", "image/png"};
revt("MNP") -> {regular, "PNM", "image/x-portable-anymap"};
revt("MPP") -> {regular, "PPM", "image/x-portable-pixmap"};
revt("TPP") -> {regular, "PPT", "application/vnd.ms-powerpoint"};
revt("SP") -> {regular, "PS", "application/postscript"};
revt("TQ") -> {regular, "QT", "video/quicktime"};
revt("AR") -> {regular, "RA", "audio/x-realaudio"};
revt("MAR") -> {regular, "RAM", "audio/x-pn-realaudio"};
revt("SAR") -> {regular, "RAS", "image/x-cmu-raster"};
revt("BGR") -> {regular, "RGB", "image/x-rgb"};
revt("MR") -> {regular, "RM", "audio/x-pn-realaudio"};
revt("FFOR") -> {regular, "ROFF", "application/x-troff"};
revt("MPR") -> {regular, "RPM", "application/x-rpm"};
revt("SSR") -> {regular, "RSS", "application/rss+xml"};
revt("FTR") -> {regular, "RTF", "text/rtf"};
revt("XTR") -> {regular, "RTX", "text/richtext"};
revt("MGS") -> {regular, "SGM", "text/sgml"};
revt("LMGS") -> {regular, "SGML", "text/sgml"};
revt("HS") -> {regular, "SH", "application/x-sh"};
revt("RAHS") -> {regular, "SHAR", "application/x-shar"};
revt("LMTHS") -> {regular, "SHTML", "text/html"};
revt("IS") -> {regular, "SI", "text/vnd.wap.si"};
revt("CIS") -> {regular, "SIC", "application/vnd.wap.sic"};
revt("OLIS") -> {regular, "SILO", "model/mesh"};
revt("TIS") -> {regular, "SIT", "application/x-stuffit"};
revt("DKS") -> {regular, "SKD", "application/x-koan"};
revt("MKS") -> {regular, "SKM", "application/x-koan"};
revt("PKS") -> {regular, "SKP", "application/x-koan"};
revt("TKS") -> {regular, "SKT", "application/x-koan"};
revt("LS") -> {regular, "SL", "text/vnd.wap.sl"};
revt("CLS") -> {regular, "SLC", "application/vnd.wap.slc"};
revt("IMS") -> {regular, "SMI", "application/smil"};
revt("LIMS") -> {regular, "SMIL", "application/smil"};
revt("DNS") -> {regular, "SND", "audio/basic"};
revt("OS") -> {regular, "SO", "application/octet-stream"};
revt("LPS") -> {regular, "SPL", "application/x-futuresplash"};
revt("CRS") -> {regular, "SRC", "application/x-wais-source"};
revt("OIPC4VS") -> {regular, "SV4CPIO", "application/x-sv4cpio"};
revt("CRC4VS") -> {regular, "SV4CRC", "application/x-sv4crc"};
revt("GVS") -> {regular, "SVG", "image/svg+xml"};
revt("FWS") -> {regular, "SWF", "application/x-shockwave-flash"};
revt("T") -> {regular, "T", "application/x-troff"};
revt("RAT") -> {regular, "TAR", "application/x-tar"};
revt("LCT") -> {regular, "TCL", "application/x-tcl"};
revt("XET") -> {regular, "TEX", "application/x-tex"};
revt("IXET") -> {regular, "TEXI", "application/x-texinfo"};
revt("OFNIXET") -> {regular, "TEXINFO", "application/x-texinfo"};
revt("ZGT") -> {regular, "TGZ", "application/x-gzip"};
revt("FIT") -> {regular, "TIF", "image/tiff"};
revt("FFIT") -> {regular, "TIFF", "image/tiff"};
revt("RT") -> {regular, "TR", "application/x-troff"};
revt("ST") -> {regular, "TS", "video/mp2t"};
revt("VST") -> {regular, "TSV", "text/tab-separated-values"};
revt("TXT") -> {regular, "TXT", "text/plain"};
revt("RATSU") -> {regular, "USTAR", "application/x-ustar"};
revt("DCV") -> {regular, "VCD", "application/x-cdlink"};
revt("LMRV") -> {regular, "VRML", "model/vrml"};
revt("VAW") -> {regular, "WAV", "audio/x-wav"};
revt("PMBW") -> {regular, "WBMP", "image/vnd.wap.wbmp"};
revt("LMXBW") -> {regular, "WBXML", "application/vnd.wap.wbxml"};
revt("LMW") -> {regular, "WML", "text/vnd.wap.wml"};
revt("CLMW") -> {regular, "WMLC", "application/vnd.wap.wmlc"};
revt("SLMW") -> {regular, "WMLS", "text/vnd.wap.wmlscript"};
revt("CSLMW") -> {regular, "WMLSC", "application/vnd.wap.wmlscriptc"};
revt("VMW") -> {regular, "WMV", "video/x-ms-wmv"};
revt("LRW") -> {regular, "WRL", "model/vrml"};
revt("MBX") -> {regular, "XBM", "image/x-xbitmap"};
revt("LMTHX") -> {regular, "XHTML", "application/xhtml+xml"};
revt("SLX") -> {regular, "XLS", "application/vnd.ms-excel"};
revt("LMX") -> {regular, "XML", "text/xml"};
revt("MPX") -> {regular, "XPM", "image/x-xpixmap"};
revt("LSX") -> {regular, "XSL", "text/xml"};
revt("DWX") -> {regular, "XWD", "image/x-xwindowdump"};
revt("ZYX") -> {regular, "XYZ", "chemical/x-xyz"};
revt("PIZ") -> {regular, "ZIP", "application/zip"};
revt("ia") -> {regular, "ai", "application/postscript"};
revt("fia") -> {regular, "aif", "audio/x-aiff"};
revt("cfia") -> {regular, "aifc", "audio/x-aiff"};
revt("ffia") -> {regular, "aiff", "audio/x-aiff"};
revt("csa") -> {regular, "asc", "text/plain"};
revt("mota") -> {regular, "atom", "application/atom+xml"};
revt("ua") -> {regular, "au", "audio/basic"};
revt("iva") -> {regular, "avi", "video/x-msvideo"};
revt("oipcb") -> {regular, "bcpio", "application/x-bcpio"};
revt("nib") -> {regular, "bin", "application/octet-stream"};
revt("pmb") -> {regular, "bmp", "image/bmp"};
revt("2zb") -> {regular, "bz2", "application/x-bzip2"};
revt("bac") -> {regular, "cab", "application/octet-stream"};
revt("fdc") -> {regular, "cdf", "application/x-netcdf"};
revt("trhc") -> {regular, "chrt", "application/x-kchart"};
revt("ssalc") -> {regular, "class", "application/octet-stream"};
revt("oipc") -> {regular, "cpio", "application/x-cpio"};
revt("tpc") -> {regular, "cpt", "application/mac-compactpro"};
revt("hsc") -> {regular, "csh", "application/x-csh"};
revt("ssc") -> {regular, "css", "text/css"};
revt("rcd") -> {regular, "dcr", "application/x-director"};
revt("rid") -> {regular, "dir", "application/x-director"};
revt("lld") -> {regular, "dll", "application/octet-stream"};
revt("smd") -> {regular, "dms", "application/octet-stream"};
revt("cod") -> {regular, "doc", "application/msword"};
revt("ivd") -> {regular, "dvi", "application/x-dvi"};
revt("rxd") -> {regular, "dxr", "application/x-director"};
revt("spe") -> {regular, "eps", "application/postscript"};
revt("lre") -> {regular, "erl", "text/plain"};
revt("xte") -> {regular, "etx", "text/x-setext"};
revt("exe") -> {regular, "exe", "application/octet-stream"};
revt("ze") -> {regular, "ez", "application/andrew-inset"};
revt("vlf") -> {regular, "flv", "video/x-flv"};
revt("fig") -> {regular, "gif", "image/gif"};
revt("ratg") -> {regular, "gtar", "application/x-gtar"};
revt("zg") -> {regular, "gz", "application/x-gzip"};
revt("fdh") -> {regular, "hdf", "application/x-hdf"};
revt("xqh") -> {regular, "hqx", "application/mac-binhex40"};
revt("lrh") -> {regular, "hrl", "text/plain"};
revt("mth") -> {regular, "htm", "text/html"};
revt("lmth") -> {regular, "html", "text/html"};
revt("eci") -> {regular, "ice", "x-conference/x-cooltalk"};
revt("fei") -> {regular, "ief", "image/ief"};
revt("segi") -> {regular, "iges", "model/iges"};
revt("sgi") -> {regular, "igs", "model/iges"};
revt("raj") -> {regular, "jar", "application/octet-stream"};
revt("epj") -> {regular, "jpe", "image/jpeg"};
revt("gepj") -> {regular, "jpeg", "image/jpeg"};
revt("gpj") -> {regular, "jpg", "image/jpeg"};
revt("sj") -> {regular, "js", "application/x-javascript"};
revt("nosj") -> {regular, "json", "application/json"};
revt("rak") -> {regular, "kar", "audio/midi"};
revt("lik") -> {regular, "kil", "application/x-killustrator"};
revt("lmk") -> {regular, "kml", "application/vnd.google-earth.kml+xml"};
revt("zmk") -> {regular, "kmz", "application/vnd.google-earth.kmz"};
revt("rpk") -> {regular, "kpr", "application/x-kpresenter"};
revt("tpk") -> {regular, "kpt", "application/x-kpresenter"};
revt("psk") -> {regular, "ksp", "application/x-kspread"};
revt("dwk") -> {regular, "kwd", "application/x-kword"};
revt("twk") -> {regular, "kwt", "application/x-kword"};
revt("xetal") -> {regular, "latex", "application/x-latex"};
revt("ahl") -> {regular, "lha", "application/octet-stream"};
revt("hzl") -> {regular, "lzh", "application/octet-stream"};
revt("u3m") -> {regular, "m3u", "audio/x-mpegurl"};
revt("v4m") -> {regular, "m4v", "video/x-m4v"};
revt("nam") -> {regular, "man", "application/x-troff-man"};
revt("em") -> {regular, "me", "application/x-troff-me"};
revt("hsem") -> {regular, "mesh", "model/mesh"};
revt("dim") -> {regular, "mid", "audio/midi"};
revt("idim") -> {regular, "midi", "audio/midi"};
revt("fim") -> {regular, "mif", "application/vnd.mif"};
revt("vom") -> {regular, "mov", "video/quicktime"};
revt("eivom") -> {regular, "movie", "video/x-sgi-movie"};
revt("2pm") -> {regular, "mp2", "audio/mpeg"};
revt("3pm") -> {regular, "mp3", "audio/mpeg"};
revt("epm") -> {regular, "mpe", "video/mpeg"};
revt("gepm") -> {regular, "mpeg", "video/mpeg"};
revt("gpm") -> {regular, "mpg", "video/mpeg"};
revt("agpm") -> {regular, "mpga", "audio/mpeg"};
revt("sm") -> {regular, "ms", "application/x-troff-ms"};
revt("hsm") -> {regular, "msh", "model/mesh"};
revt("uxm") -> {regular, "mxu", "video/vnd.mpegurl"};
revt("cn") -> {regular, "nc", "application/x-netcdf"};
revt("ado") -> {regular, "oda", "application/oda"};
revt("ggo") -> {regular, "ogg", "application/ogg"};
revt("mbp") -> {regular, "pbm", "image/x-portable-bitmap"};
revt("bdp") -> {regular, "pdb", "chemical/x-pdb"};
revt("fdp") -> {regular, "pdf", "application/pdf"};
revt("mgp") -> {regular, "pgm", "image/x-portable-graymap"};
revt("ngp") -> {regular, "pgn", "application/x-chess-pgn"};
revt("gnp") -> {regular, "png", "image/png"};
revt("mnp") -> {regular, "pnm", "image/x-portable-anymap"};
revt("mpp") -> {regular, "ppm", "image/x-portable-pixmap"};
revt("tpp") -> {regular, "ppt", "application/vnd.ms-powerpoint"};
revt("sp") -> {regular, "ps", "application/postscript"};
revt("tq") -> {regular, "qt", "video/quicktime"};
revt("ar") -> {regular, "ra", "audio/x-realaudio"};
revt("mar") -> {regular, "ram", "audio/x-pn-realaudio"};
revt("sar") -> {regular, "ras", "image/x-cmu-raster"};
revt("bgr") -> {regular, "rgb", "image/x-rgb"};
revt("mr") -> {regular, "rm", "audio/x-pn-realaudio"};
revt("ffor") -> {regular, "roff", "application/x-troff"};
revt("mpr") -> {regular, "rpm", "application/x-rpm"};
revt("ssr") -> {regular, "rss", "application/rss+xml"};
revt("ftr") -> {regular, "rtf", "text/rtf"};
revt("xtr") -> {regular, "rtx", "text/richtext"};
revt("mgs") -> {regular, "sgm", "text/sgml"};
revt("lmgs") -> {regular, "sgml", "text/sgml"};
revt("hs") -> {regular, "sh", "application/x-sh"};
revt("rahs") -> {regular, "shar", "application/x-shar"};
revt("lmths") -> {regular, "shtml", "text/html"};
revt("is") -> {regular, "si", "text/vnd.wap.si"};
revt("cis") -> {regular, "sic", "application/vnd.wap.sic"};
revt("olis") -> {regular, "silo", "model/mesh"};
revt("tis") -> {regular, "sit", "application/x-stuffit"};
revt("dks") -> {regular, "skd", "application/x-koan"};
revt("mks") -> {regular, "skm", "application/x-koan"};
revt("pks") -> {regular, "skp", "application/x-koan"};
revt("tks") -> {regular, "skt", "application/x-koan"};
revt("ls") -> {regular, "sl", "text/vnd.wap.sl"};
revt("cls") -> {regular, "slc", "application/vnd.wap.slc"};
revt("ims") -> {regular, "smi", "application/smil"};
revt("lims") -> {regular, "smil", "application/smil"};
revt("dns") -> {regular, "snd", "audio/basic"};
revt("os") -> {regular, "so", "application/octet-stream"};
revt("lps") -> {regular, "spl", "application/x-futuresplash"};
revt("crs") -> {regular, "src", "application/x-wais-source"};
revt("oipc4vs") -> {regular, "sv4cpio", "application/x-sv4cpio"};
revt("crc4vs") -> {regular, "sv4crc", "application/x-sv4crc"};
revt("gvs") -> {regular, "svg", "image/svg+xml"};
revt("fws") -> {regular, "swf", "application/x-shockwave-flash"};
revt("t") -> {regular, "t", "application/x-troff"};
revt("rat") -> {regular, "tar", "application/x-tar"};
revt("lct") -> {regular, "tcl", "application/x-tcl"};
revt("xet") -> {regular, "tex", "application/x-tex"};
revt("ixet") -> {regular, "texi", "application/x-texinfo"};
revt("ofnixet") -> {regular, "texinfo", "application/x-texinfo"};
revt("zgt") -> {regular, "tgz", "application/x-gzip"};
revt("fit") -> {regular, "tif", "image/tiff"};
revt("ffit") -> {regular, "tiff", "image/tiff"};
revt("rt") -> {regular, "tr", "application/x-troff"};
revt("st") -> {regular, "ts", "video/mp2t"};
revt("vst") -> {regular, "tsv", "text/tab-separated-values"};
revt("txt") -> {regular, "txt", "text/plain"};
revt("ratsu") -> {regular, "ustar", "application/x-ustar"};
revt("dcv") -> {regular, "vcd", "application/x-cdlink"};
revt("lmrv") -> {regular, "vrml", "model/vrml"};
revt("vaw") -> {regular, "wav", "audio/x-wav"};
revt("pmbw") -> {regular, "wbmp", "image/vnd.wap.wbmp"};
revt("lmxbw") -> {regular, "wbxml", "application/vnd.wap.wbxml"};
revt("lmw") -> {regular, "wml", "text/vnd.wap.wml"};
revt("clmw") -> {regular, "wmlc", "application/vnd.wap.wmlc"};
revt("slmw") -> {regular, "wmls", "text/vnd.wap.wmlscript"};
revt("cslmw") -> {regular, "wmlsc", "application/vnd.wap.wmlscriptc"};
revt("vmw") -> {regular, "wmv", "video/x-ms-wmv"};
revt("lrw") -> {regular, "wrl", "model/vrml"};
revt("mbx") -> {regular, "xbm", "image/x-xbitmap"};
revt("lmthx") -> {regular, "xhtml", "application/xhtml+xml"};
revt("slx") -> {regular, "xls", "application/vnd.ms-excel"};
revt("lmx") -> {regular, "xml", "text/xml"};
revt("mpx") -> {regular, "xpm", "image/x-xpixmap"};
revt("lsx") -> {regular, "xsl", "text/xml"};
revt("dwx") -> {regular, "xwd", "image/x-xwindowdump"};
revt("zyx") -> {regular, "xyz", "chemical/x-xyz"};
revt("piz") -> {regular, "zip", "application/zip"};
revt(Ext) -> {regular, Ext,
                               "text/plain"}.


